// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/vera/vera-drive-service/internal/config"
	"github.com/vera/vera-drive-service/internal/db"
	"github.com/vera/vera-drive-service/internal/logger"
	"github.com/vera/vera-drive-service/internal/middleware"
	"github.com/vera/vera-drive-service/internal/router"
	"github.com/vera/vera-drive-service/internal/url"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	zapLogger, err := logger.NewLogger()
	if err != nil {
		return nil, err
	}
	configConfig := config.NewConfig(zapLogger)
	httpMiddleware := middleware.NewHTTPMiddleware(zapLogger)
	corsMiddleware := middleware.NewCORSMiddleware(configConfig)
	authMiddleware := middleware.NewAuthMiddleware(configConfig)
	gormDB, err := db.NewDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	repository := url.NewRepository(gormDB)
	service := url.NewService(repository)
	handler := url.NewHandler(service)
	engine := router.NewRouter(httpMiddleware, corsMiddleware, authMiddleware, handler)
	app := NewApp(configConfig, engine, gormDB, zapLogger)
	return app, nil
}
