// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"vera-identity-service/internal/config"
	"vera-identity-service/internal/db"
	"vera-identity-service/internal/logger"
	"vera-identity-service/internal/middleware"
	"vera-identity-service/internal/router"
	"vera-identity-service/internal/url"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	zapLogger, err := logger.NewLogger()
	if err != nil {
		return nil, err
	}
	configConfig := config.NewConfig(zapLogger)
	httpHandler := middleware.NewHTTPHandler(zapLogger)
	corsHandler := middleware.NewCORSHandler(configConfig)
	authHandler := middleware.NewAuthHandler(configConfig)
	gormDB, err := db.NewDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	repository := url.NewRepository(gormDB)
	service := url.NewService(repository)
	handler := url.NewHandler(service)
	engine := router.NewRouter(httpHandler, corsHandler, authHandler, handler)
	app := NewApp(configConfig, engine, gormDB, zapLogger, httpHandler, corsHandler, authHandler, handler)
	return app, nil
}
